name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Run JavaScript with secret
      run: |
        node -e "console.log(process.env.GITHUB_TOKEN);"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}




